# -*- coding: utf-8 -*-
"""Wound Environment Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0st3dnxxwGff1HU5fpoHPL_dykN6yF6
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

Drug_count = 0
total_time_L = 0
drug_times = []  # 用來記錄投藥時間的列表

threshold_G = 2080000  # 投藥的threshold (FITTED:2080000)
C_dose = 23  # 每次投多少藥
check_interval = 1  # Hourly detection of bacterial population
time_hours = 96  # Total time of simulation
time_steps = 3000  # Number of time steps
detection_interval = 1/6  # detection period

t_sim = np.linspace(0, time_hours, time_steps)

G = np.zeros(time_steps)
L = np.zeros(time_steps)
C_amp = np.zeros(time_steps)

# Initial conditions
G[0] = 2000000
L[0] = 1000000
C_amp[0] = 0

k_growth_G = 0.8407  # Grams 生長速率(fitted: 0.8407)
G_max = 1400000000
gamma_G = 0.0737

k_growth_L = 0.25  # 生長斜率
L_max = 350000000  # Lactis最大值(長到飽和)

gamma_L = 0.023

lamba = 1.475  # Decay rate of AMP(fitted)

def bacterial_growth_G(G_current, C_amp_current):
    return k_growth_G * G_current * (1 - G_current / G_max) - gamma_G * C_amp_current * G_current

def bacterial_growth_L(L_current, C_amp_current):
    return k_growth_L * L_current * (1 - L_current / L_max) - gamma_L * C_amp_current * L_current

def amp_decay(C_amp_current, dt):
    return C_amp_current * np.exp(-lamba * dt)

for i in range(1, time_steps):
    # Time step
    dt = t_sim[i] - t_sim[i-1]

    G[i] = G[i-1] + bacterial_growth_G(G[i-1], C_amp[i-1]) * dt
    L[i] = L[i-1] + bacterial_growth_L(L[i-1], C_amp[i-1]) * dt
    C_amp[i] = amp_decay(C_amp[i-1], dt)

    # Check for dosing
    if np.isclose(t_sim[i] % detection_interval, 0, atol=dt/2):
        # If G bacteria population exceeds threshold, dose AMP
        if G[i] > threshold_G:
            C_amp[i] += C_dose
            Drug_count += 1
            drug_times.append(t_sim[i])  # 記錄投藥時間

    if L[i] > 7.5 * (10**5):
        total_time_L += dt

plt.figure(figsize=(12, 8))

plt.subplot(3, 1, 1)
plt.plot(t_sim, G, label="Bacterial Population (G)", color='blue')
plt.axhline(y=threshold_G, color='r', linestyle='--', label="Threshold G")
plt.xlabel("Time (hours)")
plt.ylabel("Population (G)")
plt.title("Bacterial Population Over Time (G)")
plt.legend()
plt.grid(True)

plt.subplot(3, 1, 2)
plt.plot(t_sim, L, label="L.lactis Population (L)", color='green')
plt.xlabel("Time (hours)")
plt.ylabel("Population (L)")
plt.title("L.lactis Population Over Time")
plt.legend()
plt.grid(True)

plt.subplot(3, 1, 3)
plt.plot(t_sim, C_amp, label="AMP Concentration (C_AMP)", color="orange")
plt.xlabel("Time (hours)")
plt.ylabel("AMP Concentration")
plt.title("AMP Concentration Over Time")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

print("Initial gram", G[0])
print("Threshold G:", threshold_G)
print("Dosage per event:", C_dose)
print("Growth function:", k_growth_G)
print("----")
print("Maximum G Population:", np.max(G))
print("L.lactis efficient time: ", total_time_L)
print("----")
print("Total Drug Use:", Drug_count * C_dose)
print("Drug times (Hr):", drug_times)  # 打印投藥的時間點